// Generated by Proteus Visual Designer for Arduino

// Peripheral Configuration Code (Do Not Edit)
//---CONFIG_BEGIN---
#pragma GCC push_options
#pragma GCC optimize ("Os")

#include <core.h> // Required by cpu
#include <cpu.h>
#include <bridge.h> // Required by ESP1:MQTT
#include <pubsubclient.h> // Required by ESP1:MQTT
#include <mqtt.h>

#include <SoftwareSerial.h> 

#pragma GCC pop_options

// Peripheral Constructors
CPU &cpu = Cpu;
Mqtt &ESP1_MQTT = Mqtt::instance;

//Second Serial -------------------------------------
#define RX 8
#define TX 9

SoftwareSerial mySerial(RX,TX); //Pines de Transmisión y Recepción

//MQTT Broker -----------------------------------------------------------------------------------
const char* clientID = ""; //Identificador que toma el cliente (nuestro Arduino) Ejemplos: "Arduino", "Sensor" 

const char* mqtt_server = ""; //Ejemplos: "ioticos.org" ,"192.100.25.24", "localhost"
int port  =1883;
const char* mqtt_user = ""; //Usuario
const char* mqtt_pass = ""; //Contraseña

//Topicos
String topic = ""; //Ejemplos: "Casa", "Luz" , "5npIBbWJJYbAfPr"

String subtopic1 = topic+"/LED1";
String subtopic2 = topic+"/LED2";
String subtopic3 = topic+"/POT";


//LEDS
int LED1 = 13;
int LED2 = 6;

//Funciones callbacks
void ESP1_MQTT_ConnectCallback() ;
void ESP1_MQTT_MessageCallback();


void setup(){
	//PIN CONFIG
	pinMode(LED1,OUTPUT);
	
	//MQTT BEGIN
	ESP1_MQTT.begin (clientID, mqtt_server, port, mqtt_user, mqtt_pass);

	//Definimos las funciones callbacks
	ESP1_MQTT.attachConnectHandler(&ESP1_MQTT_ConnectCallback);
	ESP1_MQTT.attachMessageHandler(&ESP1_MQTT_MessageCallback);

	//Nos conectamos
	ESP1_MQTT.connect(true);

	mySerial.begin(9600);    //Inicializar Monitor Serial 9600 bps
}

void loop(){
	//Se lee el valor en la entrada analogica 0
	int pot = analogRead(0);

	//Se publica la medicion realizada
	ESP1_MQTT.publish( subtopic3,  false).arg(pot).end();
	mySerial.println("Mensaje Publicado: "+String(pot));

	ESP1_MQTT.poll ();  //Se encarga de verificar si algun mensaje se ha recibido
	delay(500);
}


void ESP1_MQTT_ConnectCallback() {
	//Funcion se activa cuando se conecta al servidor MQTT
	ESP1_MQTT.subscribe(subtopic1,0);
	ESP1_MQTT.subscribe(subtopic2,0);
}

void ESP1_MQTT_MessageCallback() {
	//Funcion se activa cuando se recibe un mensaje en un topico subscrito
	String mqttTopic=ESP1_MQTT.readTopic();
	String mqttMessage=ESP1_MQTT.readMessage();

	String text = "Topic: "+mqttTopic+" Mensaje: "+mqttMessage;

	//Mostramos el resultado por mySerial
	mySerial.println(text);

	//Verificamos cual de los TOPIC se envio la informacion
	if (mqttTopic==subtopic1){
		int estado = toInt(mqttMessage);
		digitalWrite(LED1,estado);		
	}

	else if (mqttTopic==subtopic2){
		int valor = map(toInt(mqttMessage),0,100,0,255);
		analogWrite(LED2,valor);
	}


}



