# !/usr/bin/env python3
# Generated by Proteus Visual Designer for Raspberry Pi

# Modules
from goto import with_goto
from stddef import *
import var
import pio
import resource
from datetime import datetime

import cpu
import Ports
import MQTT
import time


def main():
	#Contructores
	pio.cpu=cpu.CPU ()
	pio.uart=Ports.UART ()
	pio.MQTT=MQTT.MQTT ()

	#UART
	pio.uart.setup (9600)

	#MQTT Server
	var.ID = "Raspberry Pi 4"
	var.server = "ioticos.org"
	var.port = 1883
	var.user = "8lDdLd8y2rRhEQi"
	var.password = "xE8ErW9wafcXOe4"

	var.Topico_Raiz = "5npIBbWJJYbAfPr"

	#Conect MQTT Server
	pio.MQTT.begin (var.ID, var.server, var.port, var.user, var.password )
	pio.MQTT.connect (True)

	#Configuration LED
	pio.cpu.pinMode (5, cpu.OUTPUT)


	pio.uart.println("Hola")
	contador = 0

	#Infinite loop
	while(True):
		print(contador)
		pio.MQTT.publish (Topico_Raiz+"/contador", 0, False, contador)
		pio.uart.println ("Mensaje Publicado: "+str(contador))
		pio.cpu.digitalWrite (5, not(pio.cpu.digitalRead(5)))
		contador+=1
		time.sleep(1)




# Command line execution
if __name__ == '__main__' :
   main()